-- Write a PL/SQL block that uses a cursor to fetch and 
-- display the names of all employees with a salary above a given threshold 
-- from an EMPLOYEES table.(Basic Cursor Usage)

-- CREATE TABLE EMPLOYEES
-- (
--     EID VARCHAR(10) PRIMARY KEY,
--     ENAME VARCHAR(10),
--     SALARY NUMBER(10)
-- );

-- INSERT INTO EMPLOYEES VALUES('E01','JENNY V',10000);
-- INSERT INTO EMPLOYEES VALUES('E02','JOSE J',20000);
-- INSERT INTO EMPLOYEES VALUES('E03','JAMES B',30000);
-- INSERT INTO EMPLOYEES VALUES('E04','JOEL G',40000);

DECLARE CURSOR C1 IS 
    SELECT ENAME,SALARY FROM EMPLOYEES WHERE SALARY>&SALARY_THRESHOLD;
BEGIN
    FOR REC IN C1 LOOP
        DBMS_OUTPUT.PUT_LINE('NAME:'||REC.ENAME||' HAS SALARY '||REC.SALARY);
    END LOOP;
END;

-- SQL> /
-- Enter value for salary_threshold: 20000
-- old   2:     SELECT ENAME,SALARY FROM EMPLOYEES WHERE SALARY>&SALARY_THRESHOLD;
-- new   2:     SELECT ENAME,SALARY FROM EMPLOYEES WHERE SALARY>20000;
-- NAME:JAMES B HAS SALARY 30000
-- NAME:JOEL G HAS SALARY 40000

-- PL/SQL procedure successfully completed.

